### PR TITLE
Methods marked with 'ForwardRef' are now always replaced by the matching methods

### PR DESCRIPTION
**Pull request by PoroCYon**
Otherwise, it would depend on the order of the assemblies passed to the repacker.

``` csharp
using System;
using System.Runtime.CompilerServices;

public static class Program
{
    [MethodImpl(MethodImplOptions.ForwardRef)]
    public static extern int GetNumber();

    static void Main(string[] args)
    {
        Console.WriteLine("The number is " + GetNumber() + ".");
    }
}
```

``` fsharp
module Program

open System

let GetNumber() = 2
```

These two programs' merged assembly would depend on the order, `GetNumber` would either be marked as `ForwardRef` or would return 2, but `ForwardRef` is usually used for merging (eg. with the ILSupport extension).

The `ForwardRef` one will now always be replaced by the other one (hence the title).

Also, I've split up the 'ILRepack.cs' file, but everything is still in the same class (partial classes).

### CODE REVIEW

**Comment by mondieu** [comment]
Is there any plan to continue with this PR? - It would be useful for the work I'm doing and I'd rather not fork and reimplement if necessary

**Comment by PoroCYon** [comment]
@mondieu I haven't touched this in a while, because it worked. il-repack developement obviously continued, and it'll be a bit hard to update this branch with every change that happened during these two years.
According to GitHub's UI, it now has merge conflicts, but it doesn't let me see *what* the conflicts actually are.

**Comment by gluck** [comment]
@mondieu what would be your use case, where do you get your uses of ForwardRef from ?
If I try to rebase this PR, I'd like to be able to test it :)

**Comment by mondieu** [comment]
@gluck - Hi again, and sorry for the radio silence, went on holiday and have been a little distracted otherwise:) - So here's my use case - I have an assembly that I'd like to write snippets of in IL to access features like generic ptr's and the like, which I'd then like to merge into the main assembly. Currently, because of the order of operations, I must instead merge the main assembly into the asm version so that methods are correctly overwritten (note that I'm willing to be wrong and be missing a flag or otherwise to make this happen) but here's the general idea..

```cs
class SomeAssembly
{
	unsafe public T this[int index]
	{
		// This method will be written in optimized IL / use features not available to the C# compiler - not sure how well this will work on an indexer, but it's where I need to use it currently ..
		[MethodImplAttribute(MethodImplOptions.ForwardRef)]
		get {return new T();}
	}
}
```

SomeAssembly.il then contains the implementation, which I'd like to be able to merge it into the main assembly rather than the other way round .. I'm quite happy to accept a custom attribute for this, but the general idea is that the main assembly should have it's methods overwritten by the others.

**Comment by gluck** [comment]
I get it, alternatives like [ILSupport](https://github.com/ins0mniaque/ILSupport) or [around roslyn](http://xoofx.com/blog/2016/05/25/inline-il-asm-in-csharp-with-roslyn/) would probably be a better fit than ILRepack for that.
But the change (once cleaned up a bit) sounds fairly small, so I'll try to embed it at some point.

**Comment by PoroCYon** [comment]
The problem with those is:

* For **ILSupport**:
  * It is no longer in active development (last commit happened one year ago).
  * Requires a few hacks to work with a newer .NET SDK (or more than a few when using mono).
  * The syntax highlighting thing doesn't cover everything (nor does [a vim script](https://github.com/vim-scripts/MSIL-Assembly) that does the same on Unices).
* For **Roslyn**:
  * The official proposal isn't implemented yet (let alone shipped).
  * Only works on Windows as far as I know.

Then again, not many people *really* know IL, as can be seen in:

* ILSupport and the vim script (idem, but as it is quite old, it wouldn't be that surprising). Aside from being seemingly dead, they miss some instructions and other keywords (such as `.hash algorithm` and the special syntax for versions).
* [The CIL backend](https://github.com/bamboo/idris-cil) of the Idris compiler (and the [language-cil](http://hackage.haskell.org/package/language-cil) library it uses) are missing some instructions (eg. those dealing with `TypedReference`s).
* Even the [Prism Code Injector](https://github.com/TerrariaPrismTeam/Prism/blob/1db199dc00a682d77d1ab4c8d0e2b7654b902837/Prism.Injector/Patcher/DNHelperExtensions.cs#L342) I wrote a year ago is wrong about the stack usage of some instructions. (I'm planning to update this today, because I might reuse the code later.)

This ought to be a bit better... (Sorry for all the complaining here.)

**Comment by KirillOsenkov** [comment]
I apologize, the changes in this PR are too invasive (it extracts most of the file into another file, destroying diffs with forks). If this is still relevant, feel free to send a new PR that is minimal.

There are a lot of forks of ILRepack, and I'm trying to keep the changes minimal to make it easy for maintainers to diff and update. This is why I'm not doing refactorings, whitespace cleanup, formatting and other changes.

**Pull request closed without merging**
