### PR TITLE
Library User Control support in XAML

### PR DESCRIPTION
**Pull request by timotei**
There we go, the next part. There are still some other cases to handle, but with this, we've got some basic use cases covered.

A quick summary on the changes:

* Added a changelog for better traceability of important changes :) I'm thinking to write here about the breaking changes (if/when they happen) or other worthy fixes. This could end up in the NuGet package changelog as well.
* Removed dependencies on the actual ILRepack class in some classes and moved to the IRepackContext
* Extracted most of the actual repack orchestration logic into separate steps, for a better organisation + minor non-logic refactorings/changes. I tried to keep them to a minimum as only to satisfy ReSharper's warnings :)
* Increased version to 2.0.0

Thanks,
Timo

### CODE REVIEW

**Comment by timotei** [comment]
OK, seems that the new NuGet-based tests are taking too much :)  That's why it fails.

**Comment by gluck** [comment]
Sounds perfect.
Tests are failing coz you're not on the tip of master, where the long-running ones are [Ignored].

Beware that latest master history is messy (ordered by date, not by git-parent-child, and some of my commits were done while my computer time was off, because I was fixing unstable tests on another project that relied on DateTime.Now).

:+1:

**Comment by timotei** [comment]
Merged from master, but Q.Q.

I cannot retrigger the job as it seems some sort of timeout-cased error, while downloading the NuGet packages.

**Comment by gluck** [comment]
Retriggered it, got the same UT error on Mahapps.Metro merge, seems the coincidence unlikely :)

**Comment by timotei** [comment]
OK, for some reason, forgot that I can (should) also run the tests locally.

Indeed, there was a WPF use case which was not properly handled :) Should be fine now.

**Comment by gluck** [comment]
:shipit:

**Comment by gluck** [comment]
To be fair, the exception reported in the logs has no helpful stack to it. I'd have expected Rx to keep the original stack around, but it seems it doesn't :(

**Pull request merged**
