### PR TITLE
Adds an option to skip merging config files

### PR DESCRIPTION
**Pull request by wmjordan**
This PR, as a workaround, addresses #283 , #255, #242

### CODE REVIEW

**Comment by BatmanPriddy** [comment]
Hello everyone, really REALLY need this feature merged into your master branch if possible.  There is no current way to skip config files, and when trying to use the utility, it throws this error:

`EXEC : error : Failed to merge configuration files: System.Data.DataException: The same table 'add' cannot be the child table in two nested relations.`

What is needed to get this merged back into the master branch, and a new version of the NuGet released?

Thanks!

**Comment by BatmanPriddy** [comment]
> This PR, as a workaround, addresses #283 , #255, #242

@wmjordan would LOVE to have this merged in if possible, and get an update NuGet package for this.  Thanks!

**Comment by wmjordan** [comment]
@BatmanPriddy 
I don't have access to this repository.
Currently I compile the source code for my own use and have no idea of publishing an NuGet thing.

You can take a look at the last commit of this PR. It just requires three modifications. You can do it and create your own NuGet if needed.

**Comment by timotei** [comment]
@wmjordan thank you for the contribution. Will do a release shortly.

**Review by timotei — APPROVED** [review]

**Pull request merged**
