### PR TITLE
Take into account explicitly implemented property indexers

### PR DESCRIPTION
**Pull request by fnajera-rac-de**
interface IA
{
    int Property [int index] { get; }
}

class A : IA
{
    IA.Property [int index] { get { ... } }
}

### CODE REVIEW

**Comment by timotei** [comment]
:+1:

**Comment by timotei** [comment]
@fnajera-rac-de Is the cecil update needed? Because looking at it (and the commit message details) it seems we're setting `false` to `top_level` instead of `fq_name` like described. And it's not clear to me why that change is needed. Can you please clarify it?

**Comment by fnajera-rac-de** [comment]
@timotei The cecil update is not needed for the original problem, explicitly implemented property indexers.

It solves another bug: custom attributes with a Type argument whose value belongs to mscorlib loses the assembly information.

Before:

image

After:

image

**Comment by KirillOsenkov** [comment]
Thank you, sorry it took 10 years!

This is now merged in https://github.com/gluck/il-repack/commit/51f810dd1c319c5b4b6e1e7f6728074655425525

Cecil has changed and the latest version now accepts a top_level optional parameter.

**Pull request closed without merging**
