### PR TITLE
add option to delay sign with a key file only containing public key

### PR DESCRIPTION
**Pull request by rohit21agrawal**
Fixes: https://github.com/gluck/il-repack/issues/222

trying to revive the pull request: https://github.com/gluck/il-repack/pull/146 

@gluck - I also incorporated your feedback of only being able to specify the public key if delaysign option is set.

Let me know what it would take to get this change in and publish a new version to NuGet.org .

We are trying to utilize this tool to merge some of our assemblies in https://github.com/nuget/nuget.client . We have given ILRepack a shot in the past, but because we delaysign our assemblies with a public key, we haven't had success and have had to revert to ILMerge.

### CODE REVIEW

**Comment by gluck** [comment]
Thanks ! LGTM

**Comment by cwuethrich** [comment]
We're just replacing ILMerge with ILRepack, but we do have the same problem. With this commit, it works. 

@gluck please let me know too, when you published a new version to nuget.org.

**Comment by rohit21agrawal** [comment]
@cwuethrich can you help me figure out if there is a way to download artifacts for this PR? How were you able to test this commit?

**Comment by gluck** [comment]
Hi @cwuethrich / @rohit21agrawal,

I have no immediate plans to release, but I enabled artifact support on AppVeyor, so you should be able to get the latest build here:
`https://ci.appveyor.com/api/project/gluck/il-repack/artifacts/build/distributions/ILRepack.2.0.16.nupkg`

LMK if it works.

Cheers.

**Comment by rohit21agrawal** [comment]
@gluck the link doesn't work. maybe you can paste it as a zip file?

**Comment by gluck** [comment]
Sorry I missed an 's' in the URL, edited it, LMK

**Comment by cwuethrich** [comment]
@rohit21agrawal I debugged this part and built it with my local clone.
@gluck thanks for the link, it worked (Y)

**Comment by rohit21agrawal** [comment]
@gluck would you have any concerns if we publish this package to a publicly consumable myget feed for the sake of our CI?

**Comment by gluck** [comment]
No concern, maybe considering naming the version differently to avoid confusion with the official release when it comes, but up to you.

**Comment by gluck** [comment]
FYI `2.0.16` was released

**Pull request merged**
