### PR TITLE
Added nuget-based integration tests

### PR DESCRIPTION
**Pull request by gluck**
- Roundtrips a nuget package assemblies using ILRepack
- May become troublesome to troubleshoot
- But easy to build upon and add more assemblies
- Doesn't check much of the merging code, but will eventually check much
of the IL R/W logic
- Will take forever to run, let's hope AppVeyor copes with it

### CODE REVIEW

**Comment by tephe** [comment]
Looks awesome. I'll update my branch to use these tests instead of manually added sharpdevelop assemblies. :+1: @emanuelvarga would probably find these useful too in his thread executor implementation. 

You want to merge into master eventually? The nupkg_tests branch will need to be updated otherwise. I'm thinking that the performance tuning will be done on tests branch more easily.

Can they integrate with ncrunch easily? The powerful execution time ncrunch provides because of IL injection is very useful to spot bottlenecks.

**Comment by gluck** [comment]
They'll get merged, if they get enough +1's :smile:
Eventually it'll hurt your NCrunch experience won't it ? (they can take tens of seconds to execute).

On @timotei branch, he create an integration tests project, maybe I can move them to such a project when it gets merged. Or add a category. You tell me !

**Comment by timotei** [comment]
I'd say moving to the integration tests project would be a tad better than a category.

**Comment by gluck** [comment]
Yeah, I'll move them when we merge wpf branch, didn't want to have the conflicts by creating the project here as well.
Regarding the msbuild build async, is this the lib ? https://www.nuget.org/packages/MSBuild.Extension.Pack/

**Comment by tephe** [comment]
Sorry for the late response, just got back from vacation. I think moving it to the integration tests project from timotei's branch is the best solution.
I view categories as additional documentation on the tests. E.g.: Integration tests could be performance , simple lib merges or WPF. But it's additional documentation that we need to maintain.

**Comment by timotei** [comment]
@gluck 
https://www.nuget.org/packages/Microsoft.Bcl.Async/ This is the package

**Comment by gluck** [comment]
Added the lib to the dataset, simple roundtrip seems to work fine.

**Pull request merged**
