### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by timotei**

### CODE REVIEW

**Comment by gluck** [comment]
cherry-picked the repack fix, dropped the other one (I wanna keep using VS 2015 :tada: )

Thx !

**Comment by timotei** [comment]
VS 2015/C#6 sounds good. Do we want to use that in the main application as well?

**Comment by gluck** [comment]
Good question, why couldn't we ? it forces ppl to use VS 2015, but anyway using it in tests does as well

**Comment by timotei** [comment]
I need to check if we can build (yet) C# 6 code on unix, with msbuild 14. Because if not, we could keep C# 6 features out of main code until we've got proper support; that way we can still compile ILRepack itself if we want (xbuild just the project itself)

**Comment by gluck** [comment]
true, didn't think about unix/mono build, would be nice to keep that.

**Comment by timotei** [comment]
OK, so we should be good enough to use VS 2015 (community edition is free for all so no problem wrt license) and the linux build works fine (except right now it doesn't, but it's some other reason I see)

**Pull request closed without merging**
