### PR TITLE
Initial WPF Support

### PR DESCRIPTION
**Pull request by timotei**
So, here we go, here it is the initial WPF merging support. It's only the first step, the rest soon to come. Now, on to the mandatory #walloftext:

A couple of insights on the change:
* Extracted most of the Import + Copy logic into a separate class for better management. Probably will extract more components later as I see fit for adding the rest of WPF (resource-related merging).
* The application has been upgraded (for now) to .NET 4.0 due to the way we do the BAML patching. See below for details
* We now have a suite (actually one one test for now) of integration tests which are very handy to test the actual functionality. I'll probably add some non-WPF just to ensure some basic coverage of the actual patching.
* Had to make public some classes due to the way interfaces work. However I'll probably be able to fix this in another PR, after I reorganise a bit more the repacking process to be able to be more self-contained, thus better managing the dependencies.

Questions on moving forward:
* I was thinking to bump the major version to 2.0. What do you think? It will help with any breaking changes for the interface of the ILRepack class & rest + since it has a major feature we might advertise it like that.
* I maintained the initial year (2011) in the copyright notices for the initial code. Let me know if you want me to update it (to 2015 or "2011-2015").
* In order to do the proper patching the internal WPF load mechanism will need to load the assemblies into the AppDomain. That is bad and good at the same time, but we have to deal with it for now. For that, I had to bump the ILRepack runtime to .NET 4 so we are able to load net40 libs. However, this means that in order to be able to repack WPF 4.5 apps, we'll need to bump the .NET runtime version even more. This brings the question: how should we handle this better? Create/deploy ILRepack versions for multiple .NET FW versions coupled with "target assembly + libraries" check on the .NET FW version and warn & exit early?

Thanks,
Timo

### CODE REVIEW

**Comment by timotei** [comment]
This is weird. The integration test should pass. AppVeyor uses a normal Windows machine with GUI... 

Maybe we should use AppVeyor's included test running *as well*, to at least get some help on why the tests fail? (I'll be able to see any test output then, unlike now).

**Comment by timotei** [comment]
OK, it seems 2 seconds wait time was not enough :D.

**Comment by gluck** [comment]
Dependency on loading the assembly is a bit problematic. Did you consider BAML R/W alternatives to the reflection one ?
https://blog.lextudio.com/2014/06/summary-of-baml-readerwriter-implementations/

Such as this one ?
https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Renamer/BAML/BamlRW.cs

**Comment by timotei** [comment]
Yeah, the ILSpy Baml decompiler was the first one I've looked over, but since it hadn't the opposite operation (writing BAML) implemented, I looked over other alternatives (and remembered locbaml) as I considered the reverse engineering (from the PoV that BAML format is not "officially" known/published - unless you consider the reference source) of writer a last resort choice.

But haven't thought yet about the other possible BAML writers (like in that obsfucator). Thanks for the tip, will take a look over that.

One of the reasons I chose MS's implementation (at least for the initial support) was that it reused the core/original BAML writers/readers - which are potentially better (supported) than the reverse-engineered ones, except maybe if "getting inspired" by the MS implementation when writing the non-MS ones.

Anyway, will take a look at the alternatives and get back.

**Comment by timotei** [comment]
Good news. Managed to get the repack patching work with the ConfuserEx BAML Reader/Writer. No more the need to load the assemblies at runtime nor to upgrade the .NET FW (although the upgrade to 4.0 would be welcome :) )

**Comment by gluck** [comment]
:shipit:

**Comment by lextm** [comment]
It is bad idea to pick up the Confuser patch as it is covered by GPL. 

If you don't revert, you will have to release IL Repack code base fully under GPL.

**Comment by lextm** [comment]
https://github.com/yck1509/ConfuserEx/issues/225

More details regarding the source code licensing can be found here.

**Comment by timotei** [comment]
Thanks for the feedback. It seems we're fine for now, according to yck1509's response on that issue :)

**Comment by lextm** [comment]
Yep, so wonderful that piece of code is now under MIT, and can be used in other open source projects.

**Pull request merged**
